theme: osuny
_merge: deep
params:
  plausible: www.pourparlers.studio
  summary:
    position: content
  search:
    active: false
  components:
    lightbox:
      disabled: true
  projects:
    index:
      layout: list
  posts:
    index:
      layout: grid
      options:
        summary: false
        categories: false
  home:
    head:
      title: site